import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight, BadgeIndianRupee, BarChart3, Check, ChevronDown,
  CircleCheck, ClipboardCheck, Eye, Layers3,
  Megaphone, MessageCircle, MousePointerClick, RefreshCw,
  Search, SlidersHorizontal, Target,
  Users, Video, Workflow, X,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Google & Meta Ads for Coaching Institutes",
  description: "Admission-focused Google Ads, Meta Ads, YouTube, remarketing, landing pages, conversion tracking and lead-quality optimisation for coaching institutes.",
  keywords: ["Google Ads for coaching institutes", "Meta Ads for coaching institutes", "education PPC agency", "admission lead generation", "Facebook ads for training institutes", "coaching institute digital marketing"],
  alternates: { canonical: "/services/ads" },
  openGraph: { title: "Google & Meta Ads for Coaching Institutes | ErnestPath", description: "Turn paid media into qualified counselling opportunities and measurable admissions—not a dashboard full of clicks.", url: "/services/ads", siteName: "ErnestPath", type: "website" },
  twitter: { card: "summary_large_image", title: "Google & Meta Ads for Coaching Institutes | ErnestPath", description: "Campaign strategy, creative, landing pages, tracking and admissions-funnel optimisation for education brands." },
  robots: { index: true, follow: true },
};

const audiences = [
  ["NEET & JEE coaching", "Search campaigns for high-intent course and city queries, Meta campaigns for parents and students before final comparison, scholarship or counselling funnels, and remarketing during the admission window."],
  ["Government-exam institutes", "Campaigns organised by examination, attempt cycle, language, classroom or online mode, with landing pages that explain faculty, test series, schedules and realistic preparation support."],
  ["Software training institutes", "Career-focused campaigns for technology programmes, demo classes and cohort launches, supported by curriculum, projects, mentor credibility, placement-process clarity and lead qualification."],
  ["Language-training centres", "Course-level campaigns for spoken English, IELTS, PTE, OET and other programmes, separated by learner goal, proficiency, location, schedule and online or classroom preference."],
  ["Overseas-education consultancies", "Country, intake and counselling campaigns with careful qualification for study goal, academic stage and preferred destination, plus longer remarketing journeys for complex decisions."],
  ["Tuition & academic centres", "Radius-aware local campaigns for class, curriculum and neighbourhood searches, with parent-friendly proof, convenient contact paths and branch-specific landing experiences."],
  ["Skill-development academies", "Campaigns for design, finance, business, creative and vocational programmes where outcome, portfolio, certification, teaching format and learner suitability must be explained clearly."],
  ["Multi-branch education brands", "Location-controlled campaigns, branch-specific budgets and landing pages, consistent tracking, and reporting that prevents one strong city from hiding waste or weak follow-up elsewhere."],
];

const failures = [
  ["Optimising for the cheapest lead", "A low cost per lead can look successful while counsellors receive accidental form submissions, unreachable numbers or people seeking a different course. Campaigns need a shared definition of a qualified lead and downstream status feedback—not a race toward the cheapest form fill."],
  ["Sending every click to the homepage", "The advertisement promises one course or outcome, but the homepage asks visitors to navigate again. That break in message, course and intent lowers trust and wastes paid attention. Priority campaigns need focused landing pages that continue the exact conversation begun by the ad."],
  ["Using one campaign for every course", "Courses differ in value, audience, admission cycle, geography and decision time. Combining them hides performance and lets high-volume searches consume budget intended for priority batches. Account structure should reflect the institute's actual portfolio and enrolment goals."],
  ["Generic creative without evidence", "Posters containing a logo, faculty photo and large phone number rarely answer why somebody should stop, believe or enquire. Effective creative connects a specific learner problem with a clear programme, credible evidence and a proportionate next step."],
  ["Tracking only platform-reported leads", "Google and Meta can record a conversion, but they do not automatically know whether the person answered, qualified, attended counselling or paid a fee. Without CRM or admissions feedback, the algorithm and the institute both optimise using incomplete information."],
  ["Ignoring counsellor response time", "A promising lead becomes cold when calls begin hours later, nobody owns the enquiry or follow-up stops after one attempt. Advertising cannot repair an unmanaged admissions process. Lead routing, response expectations and status discipline are part of campaign readiness."],
  ["Scaling before the system is stable", "Increasing budget does not fix a weak offer, inaccurate tracking, narrow creative library or poor landing experience. It usually multiplies the existing weakness. Scale should follow validated demand, dependable conversion signals and the team's capacity to handle more enquiries."],
  ["Treating admission season like a constant", "Search demand, urgency and competition change around exam results, academic calendars, counselling dates and batch starts. Budgets, messages and offers need a seasonal plan rather than the same campaign running unchanged for twelve months."],
];

const system = [
  ["Demand", "We identify where active demand exists, how it changes by city and season, and whether search, social, video or a combined journey is appropriate."],
  ["Offer", "The campaign gives a suitable reason to act: counselling, a demo, course guidance, an assessment, a scholarship test or a clearly described batch—not an empty ‘enquire now’."],
  ["Message", "Every ad connects one audience problem to one relevant programme and one truthful next step. Claims must be specific, supportable and consistent with the landing page."],
  ["Audience", "Targeting combines intent, geography, exclusions, first-party information where permitted, and platform learning. It is never treated as a substitute for a strong message."],
  ["Destination", "The landing page continues the advertisement, answers objections, supplies evidence and works comfortably on mobile. The homepage is used only when it genuinely matches the campaign."],
  ["Capture", "Forms ask enough to route and qualify the enquiry without creating unnecessary abandonment. Calls, WhatsApp and booking actions are tracked according to the agreed journey."],
  ["Follow-up", "Lead source, course, location and campaign context reach the admissions team. Ownership and status updates turn a notification into an operating process."],
  ["Learning", "Search terms, creative response, landing behaviour and admissions outcomes inform exclusions, budget shifts, new tests and scale decisions."],
];

const services = [
  { icon: Target, title: "Campaign strategy & admission economics", direct: "Campaign strategy converts batch targets, fee value, seat availability and admission timing into a practical media plan.", problem: "A monthly budget chosen without admission economics can be either too small to learn or too large for the institute to handle responsibly.", solution: "We establish priority courses, locations, capacity, realistic funnel stages and acceptable acquisition economics before choosing channels. The plan distinguishes business targets from platform forecasts and avoids presenting estimates as guarantees.", includes: ["Batch and revenue priorities", "Course-value analysis", "Audience and decision mapping", "Seasonality planning", "Funnel assumptions", "Budget scenarios", "Channel roles", "Measurement definitions"] },
  { icon: Search, title: "Google Search Ads", direct: "Google Search Ads capture people actively looking for a course, coaching option, training provider or counselling support.", problem: "Broad keywords, weak negatives and generic ads can pay for job searches, free resources, unrelated locations and information-only clicks.", solution: "We organise campaigns by course, intent and geography; write relevant ads; review actual search terms; and send valuable clicks to a closely matched page. Brand, competitor and non-brand demand are kept interpretable.", includes: ["Keyword and intent research", "Campaign and ad-group structure", "Responsive search ads", "Negative-keyword system", "Location and schedule controls", "Assets and extensions", "Search-term review", "Bid and budget optimisation"] },
  { icon: Megaphone, title: "Meta Facebook & Instagram Ads", direct: "Meta Ads create and capture consideration through relevant messages, visual proof and repeated exposure across Facebook and Instagram.", problem: "Interest targeting alone does not produce quality. Broad audiences paired with generic posters often generate cheap but poorly informed enquiries.", solution: "We build creative angles around learner problems, course fit, outcomes, teaching method, faculty or admission moments. Audience testing and platform automation are used with qualification, exclusions and downstream feedback.", includes: ["Campaign objective selection", "Audience hypotheses", "Feed, Story and Reel formats", "Lead-form or website journeys", "Creative angle testing", "Retargeting audiences", "Placement review", "Quality-focused optimisation"] },
  { icon: Video, title: "YouTube & video campaigns", direct: "Video campaigns help an institute explain a considered programme, demonstrate teaching credibility and remain familiar before a student is ready to enquire.", problem: "Video budget is wasted when a television-style brand film is shown broadly with no audience logic, sequence or measurable next action.", solution: "We define short hooks, proof-led videos, faculty explanations, student-work stories and remarketing sequences. YouTube is used where the decision needs education or repetition, not simply because video inventory is available.", includes: ["Video campaign strategy", "Script and hook direction", "Audience and topic signals", "Short and longer formats", "Sequenced messaging", "Remarketing", "Landing-page alignment", "View and conversion analysis"] },
  { icon: RefreshCw, title: "Remarketing & return journeys", direct: "Remarketing reconnects with people who visited, watched, engaged or began an enquiry but still need information or confidence.", problem: "Institute decisions rarely happen in one visit, yet many campaigns repeatedly show the same introductory ad to everybody—or follow people long after relevance has ended.", solution: "We segment by meaningful behaviour and use a limited sequence of proof, objection answers, deadlines or next steps. Windows and exclusions are adjusted to course cycles, consent choices and platform capabilities.", includes: ["Website visitor audiences", "Video-viewer audiences", "Engagement audiences", "Form-start segments", "Course-specific messaging", "Frequency review", "Converted-user exclusions", "Admission-window controls"] },
  { icon: Layers3, title: "Campaign landing pages", direct: "A campaign landing page gives one audience a focused explanation of one programme or admission opportunity.", problem: "When an ad and destination use different promises, visitors must rebuild context and are more likely to leave before understanding the offer.", solution: "We design or improve mobile-first pages with clear course fit, delivery details, proof, objections, FAQs and a proportionate action. Search foundations are retained when a page also deserves organic visibility.", includes: ["Message-match copy", "Course and batch information", "Mobile-first hierarchy", "Relevant proof", "Objection handling", "Focused forms and CTAs", "Thank-you journey", "Speed and accessibility foundations"] },
  { icon: Eye, title: "Creative strategy & testing", direct: "Creative strategy produces a repeatable set of truthful messages and formats, not a random collection of admission posters.", problem: "Creative fatigue, vague claims and identical layouts make audiences ignore the institute. Changing colours is not a meaningful test.", solution: "We plan angles, hooks, evidence, formats and calls to action around distinct hypotheses. Asset production responsibilities are defined in scope; where filming is required, we provide briefs or direction unless production is included.", includes: ["Audience objections", "Hook and headline bank", "Proof-led concepts", "Faculty and learner formats", "Static and short-video briefs", "Variation matrix", "Claim verification", "Fatigue monitoring"] },
  { icon: ClipboardCheck, title: "Lead forms & qualification", direct: "Lead qualification balances completion ease with the information counsellors need to prioritise and respond usefully.", problem: "A name and phone number create volume without context, while a long application form suppresses genuine interest too early.", solution: "We select progressive fields appropriate to the course value and decision stage. Higher-intent actions may request course, location, education level, preferred mode or schedule, while low-friction actions collect less.", includes: ["Field and form strategy", "Course selection", "Branch or city capture", "Schedule and mode preference", "Conditional questions", "Spam reduction", "Consent language placement", "Confirmation and next steps"] },
  { icon: BarChart3, title: "Conversion tracking & analytics", direct: "Conversion tracking records meaningful actions and creates a defensible link between campaign spend, enquiries and downstream admissions outcomes.", problem: "Duplicate tags, button-click conversions and untested thank-you events inflate performance. Privacy changes also make perfect attribution impossible.", solution: "We audit and configure the agreed Google, Meta and analytics events; document what each conversion means; use UTMs; and test the journey. Server-side or offline integrations are scoped when they materially improve decision-making.", includes: ["GA4 and Tag Manager review", "Google Ads conversions", "Meta Pixel foundation", "Form and booking events", "Call and WhatsApp clicks", "UTM governance", "Duplicate-event prevention", "Tracking quality checks"] },
  { icon: Workflow, title: "CRM & counsellor feedback loop", direct: "A feedback loop tells marketing which leads became qualified conversations, visits, demos, applications and admissions.", problem: "Platforms learn from form submissions while the real business outcome remains inside calls, spreadsheets or counsellor memory.", solution: "We map source data into an existing CRM or agreed workflow and define usable statuses. When supported, qualified or admitted outcomes can be returned to advertising platforms using appropriate technical and privacy controls.", includes: ["Source and campaign capture", "Lead routing", "Ownership fields", "Status definitions", "Follow-up context", "Qualified-lead reporting", "Offline conversion planning", "Counsellor feedback rhythm"] },
  { icon: BadgeIndianRupee, title: "Budget, bidding & seasonality", direct: "Budget management allocates spend according to priority, learning needs, capacity and changing admission demand.", problem: "A single daily budget can overfund easy volume while strategic courses, cities or high-value programmes receive too little data to improve.", solution: "We separate controllable priorities, monitor pacing and use automated bidding only with suitable objectives and signal quality. Performance Max is considered after strategy and conversion data—not used as a default shortcut.", includes: ["Course and city allocation", "Daily and monthly pacing", "Bid-strategy selection", "Learning-period expectations", "Admission-calendar changes", "Capacity constraints", "Reallocation rules", "Scale readiness checks"] },
  { icon: SlidersHorizontal, title: "Optimisation & decision-ready reporting", direct: "Optimisation turns campaign, creative, landing-page and admissions evidence into deliberate weekly and monthly decisions.", problem: "Reports filled with impressions, reach and charts can hide whether the institute is gaining suitable conversations or filling the intended batch.", solution: "We monitor leading diagnostics and business outcomes together. Reports explain what changed, what was learned, where quality weakened, and what action follows—while recognising attribution limitations.", includes: ["Search-term optimisation", "Audience and placement review", "Creative comparison", "Landing-page findings", "Lead-quality analysis", "Budget changes", "Experiment log", "Monthly decision summary"] },
];

const channels = [
  ["Google Search", "Captures active demand", "People already searching for a course, institute, class, coaching or location", "Course-specific searches, urgent comparisons and local demand", "Limited search volume and expensive auctions require disciplined query control"],
  ["Meta", "Creates and captures consideration", "Students or parents whose need exists but whose institute choice is not yet fixed", "New batches, demos, scholarship events, proof-led stories and visual programmes", "Creative quality and lead qualification matter more than narrow interest stacking"],
  ["YouTube", "Explains and builds familiarity", "People researching a complex course or repeatedly encountering the decision", "Faculty authority, methodology, learner stories and remarketing sequences", "Views are not admissions; the video and next step need a defined role"],
  ["Remarketing", "Supports return and decision completion", "Known visitors, viewers, engagers or incomplete enquirers", "Objection answers, proof, deadlines and course-specific reminders", "Requires sufficient audience size, reasonable frequency and timely exclusions"],
];

const metrics = [
  ["Reach & impression", "Did the intended market have an opportunity to see the message? Useful for delivery context, not proof of demand or admissions."],
  ["Click & landing view", "Did the message create enough relevance for a visit, and did the destination actually load? Click-through rate and cost per click are diagnostic signals."],
  ["Enquiry", "Did a person submit, call, message or book the agreed action? The event must be validated and deduplicated before its cost is trusted."],
  ["Qualified lead", "Did the person match the course, geography, eligibility and reasonable intent criteria? Cost per qualified lead is often more useful than raw cost per lead."],
  ["Counselling or demo", "Did the lead progress into a real conversation, visit, assessment or demo? This stage reveals the combined effect of targeting, information and follow-up."],
  ["Application or admission", "Did the opportunity produce the institute's defined commercial outcome? Admission cost and revenue context guide sustainable scaling, with attribution limits stated."],
];

const process = [
  ["01", "Diagnostic and goals", "We review priority courses, locations, seats, fees, admission windows, past campaigns, website experience, lead records and counsellor capacity. The output is a shared problem definition rather than an immediate media launch."],
  ["02", "Tracking and account audit", "Existing Google Ads, Meta, analytics, Tag Manager and CRM access is reviewed. We identify missing, duplicate or misleading conversions and preserve useful account history wherever possible."],
  ["03", "Audience and demand research", "Search language, geographic demand, competitor messages, audience objections and decision timing are investigated. Research supports channel choice; it does not claim exact future volume."],
  ["04", "Offer and funnel design", "We select the action that fits each audience stage—course counselling, demo, assessment, brochure, scholarship test or direct admission conversation—and define what happens after submission."],
  ["05", "Account architecture", "Campaigns, budgets, locations, objectives, exclusions and naming are organised so performance remains interpretable by course and market."],
  ["06", "Landing experience", "We create or improve the destination to match the ad, answer decisive questions, establish credibility and capture useful enquiry context on mobile devices."],
  ["07", "Creative and copy", "Search ads, visual concepts, short-video directions and variations are prepared around explicit hypotheses. Factual claims and supplied evidence remain subject to institute approval."],
  ["08", "Build and quality review", "Campaign settings, URLs, forms, events, audiences and policies are checked. Platform approval remains controlled by Google or Meta and cannot be guaranteed by ErnestPath."],
  ["09", "Controlled launch", "Budgets begin at an agreed level, delivery is monitored and obvious query, placement, technical or routing problems are corrected before expansion."],
  ["10", "Lead-quality loop", "Counsellor feedback and CRM status reveal whether leads are relevant, contactable and progressing. The campaign is adjusted using outcome quality, not only platform lead totals."],
  ["11", "Experiment and refine", "We test one useful variable at a time where volume permits: message, creative angle, query group, audience, offer, field, landing section or bidding approach."],
  ["12", "Scale or reallocate", "Budget increases follow stable tracking, repeatable demand, acceptable acquisition economics and operational capacity. Otherwise, spend is reallocated, the offer is revised or the test is stopped."],
];

const roadmap = [
  ["Month 1", "Build a trustworthy measurement and launch foundation", "Audit accounts and tracking; define qualified lead; research demand; structure campaigns; prepare landing pages, forms, creative and routing; launch in controlled stages."],
  ["Month 2", "Replace assumptions with campaign and admissions evidence", "Review search terms, placements, audience response, creative fatigue, landing behaviour, contactability and counsellor statuses. Remove waste and run focused tests."],
  ["Month 3", "Concentrate spend where the full funnel is strongest", "Compare course, city, channel and creative quality; improve weak handoffs; document repeatable patterns; scale suitable segments or redirect budget before the next admission window."],
];

const comparison = [
  ["Success measure", "Cheap leads and platform conversions", "Qualified conversations, counselling progress and admission economics"],
  ["Campaign structure", "One campaign for every course", "Course, intent, city and season remain interpretable"],
  ["Creative", "Generic posters changed occasionally", "Planned messages, evidence, formats and fatigue control"],
  ["Landing page", "Homepage or instant form by default", "Destination chosen for intent, information and qualification"],
  ["Tracking", "Pixel installed; every click is celebrated", "Tested events, UTMs, source capture and stated attribution limits"],
  ["Lead quality", "Declared a sales-team problem", "Shared criteria and a counsellor-to-campaign feedback loop"],
  ["Reporting", "Impressions, CTR and monthly screenshots", "Decisions, experiments and funnel movement explained"],
  ["Scaling", "Raise budget when CPL falls", "Scale after signal quality, economics and follow-up capacity stabilise"],
];

const faqs = [
  ["What advertising services does ErnestPath provide for coaching institutes?", "ErnestPath plans and manages admission-focused Google Search, Meta Facebook and Instagram, selected YouTube and remarketing campaigns. The engagement can also include campaign landing pages, creative and copy direction, lead forms, conversion tracking, analytics, CRM or lead-flow integration, budget management, optimisation and reporting. Scope is built around the institute's priority programmes and admissions process; it is not a fixed list of channels switched on whether or not they suit the audience."],
  ["Should our institute use Google Ads or Meta Ads?", "Google Search is usually strongest when enough people actively search for the course, exam, training topic or nearby institute. Meta can reach and educate prospective students or parents before they make a direct search and gives creative more influence. Many institutes benefit from distinct roles for both: Search captures existing intent, Meta creates or reinforces consideration, and remarketing supports return visits. The recommendation depends on demand, geography, programme value, evidence, admission cycle and the quality of available creative."],
  ["How much ad budget does a coaching institute need?", "There is no responsible universal minimum. Budget depends on search volume, auction costs, city, course value, audience size, number of programmes, conversion rate, learning needs and the institute's ability to follow up. We prepare a scenario using available data and clearly separate assumptions from known numbers. A budget must be large enough to gather useful evidence without exposing the institute to uncontrolled risk. Media spend is normally paid directly by the institute to Google or Meta and is separate from ErnestPath's service fee."],
  ["How much does campaign management cost?", "Management cost depends on channel count, course and city complexity, creative volume, landing-page requirements, tracking condition, reporting depth and integration work. After a diagnostic, the proposal states the monthly fee, one-time setup work where applicable, media spend, third-party costs, deliverables and responsibilities. We avoid quoting only a percentage of ad spend when that would hide the strategic, creative, technical and admissions-process work required to improve the full funnel."],
  ["How soon will ads generate leads?", "Campaigns can begin producing traffic and enquiries soon after launch and platform approval, but immediate volume is not the same as stable quality. Early weeks reveal search terms, creative response, landing-page behaviour and contactability. A dependable pattern usually needs sufficient data, timely counsellor feedback and several controlled improvements. Seasonality and low search volume can extend learning. ErnestPath does not promise a fixed number of leads by a fixed day because the platform, market, offer and admissions operation all affect the result."],
  ["Can you guarantee leads or admissions?", "No. We cannot honestly guarantee a lead or admission count because auction conditions, demand, course quality, pricing, brand reputation, platform policies, website experience and counsellor performance are not fully controlled by an agency. We can commit to the agreed research, implementation, tracking, management and optimisation process. Forecasts are planning estimates, not promises. Our reporting connects media activity with qualified-lead and admission information wherever reliable data is available so decisions can be made transparently."],
  ["How do you improve lead quality?", "We improve quality through tighter intent and geography, accurate exclusions, course-specific messages, evidence-rich landing pages, appropriate form questions, confirmation steps and rapid feedback from counsellors. Quality is defined before launch using criteria such as programme interest, location, eligibility, schedule and genuine contactability. We then compare campaigns by qualified-lead rate and downstream progress, not only raw cost per form. Advertising cannot eliminate every unsuitable lead, and overly restrictive qualification can also exclude good prospects, so the balance is tested."],
  ["Why are our Meta leads cheap but not answering calls?", "Common causes include low-friction instant forms, accidental submissions, broad creative that attracts curiosity, weak expectation-setting, delayed follow-up and repeated attempts from unfamiliar numbers. We examine lead timestamp, placement, form completion, course clarity, confirmation message and counsellor response pattern. Options may include higher-intent forms, qualifying questions, a website journey, schedule selection, WhatsApp confirmation or adjusted optimisation. The right correction depends on evidence; simply narrowing the audience often raises cost without fixing intent."],
  ["Do we need a separate landing page?", "A separate page is valuable when the campaign promotes one course, batch, branch, scholarship test, webinar or demo and the existing website does not continue that exact message. The page should answer suitability, curriculum, delivery, duration, proof, objections and next steps without unnecessary distraction. A strong existing course page can sometimes serve the same purpose. We do not create landing pages only to hide information and force a form; clarity often improves both conversion quality and counsellor conversations."],
  ["Can you run ads if we do not have a good website?", "Yes, but the route must be chosen carefully. Meta or platform lead forms may allow an initial test, while a focused campaign page can be built before a complete website redesign. For considered or high-value programmes, a weak website can still reduce confidence when prospects research the institute after seeing an ad. We will identify the minimum viable destination and explain the risk. ErnestPath can also build an admission-focused website through our website development service when the wider digital foundation needs improvement."],
  ["Do you create ad graphics and videos?", "Creative strategy, copy, concepts, briefs and agreed static variations can be included. Original filming, photography, complex motion production, actors, studio work or large editing requirements are priced or arranged separately unless the proposal specifically includes them. We help the institute plan useful raw material such as faculty explanations, classroom demonstrations, student projects and verified outcomes. Asset responsibilities, revision limits and approval timelines are documented because a steady creative supply is essential for Meta and video performance."],
  ["What information do you need from our institute?", "We need accurate course, batch, delivery, fee and location information; audience eligibility; differentiators; faculty and methodology details; verified results or reviews; brand assets; account access; historical performance; and the admissions team's qualification and follow-up process. The institute remains responsible for verifying claims, permissions and supplied media. Faster, accurate input improves launch quality. When evidence is missing, we recommend a truthful alternative rather than inventing rankings, placements, success rates or urgency."],
  ["Who owns the Google Ads and Meta accounts?", "The institute should own its primary advertising, analytics and business assets whenever platform structure allows. ErnestPath works through appropriate partner or user access, and the institute pays media platforms directly unless a different written arrangement is required. This protects continuity and makes account history portable. We document essential access during onboarding and remove our access at the end of the engagement after agreed handover. We do not hold an institute's campaign history hostage inside an undisclosed agency-owned account."],
  ["How is conversion tracking set up?", "We define conversions first, then implement the appropriate combination of Google Tag Manager, GA4, Google Ads tags, Meta Pixel, form events, thank-you pages, click events and CRM source fields. Events are tested to reduce duplicates and false signals. Enhanced, server-side or offline conversion features may be scoped when technically useful and permitted. Tracking is never perfect: consent choices, device changes, call behaviour and platform attribution models create gaps, so reporting states assumptions rather than presenting every attributed conversion as absolute truth."],
  ["Can ads integrate with our CRM and counsellors?", "Yes, when the selected CRM offers a usable API, webhook or supported connector. We can pass course, location, source, campaign and UTM context; assist with routing; and define statuses such as new, contacted, qualified, counselling booked, attended, applied, admitted or lost. Exact integration depends on the CRM, permissions and workflow. A complex custom admissions platform is scoped separately. The team still needs clear ownership and disciplined updates, because technology cannot infer call quality from an untouched lead record."],
  ["Can you advertise several branches or cities?", "Yes. We separate locations when budgets, courses, demand, creative or operational performance need independent control. Ads and landing pages should use genuine branch details, accurate service areas and locally relevant proof. We monitor geographic reports and exclude areas the institute cannot serve. Multi-location structure avoids letting one high-volume city absorb the entire budget. However, extremely small audiences may need consolidation to generate enough data, and platform location targeting is not perfectly precise."],
  ["Will Google or Meta approve every education ad?", "No agency controls platform approval. Google and Meta apply policies, automated reviews and account-level risk systems that can change. We prepare campaigns to follow current requirements, avoid deceptive claims and supply requested business information, but an ad or account can still be limited or rejected. ErnestPath can investigate and submit a permitted review; we cannot bypass policy, disguise prohibited content, create replacement accounts to evade enforcement or guarantee reinstatement."],
  ["How do you report advertising performance?", "Reporting is organised around the agreed funnel: spend and delivery, visits, enquiries, qualified leads, counselling or demo progress, applications and admissions where the institute supplies reliable statuses. We include diagnostic measures such as search terms, click-through rate, cost per click, frequency and landing performance when they explain a decision. A useful report states what changed, what was learned, limitations in the data and what happens next. Platform screenshots alone are not treated as strategy."],
  ["What happens during the first 90 days?", "The first month establishes tracking, demand research, account structure, landing experience, creative, lead flow and a controlled launch. The second month removes obvious waste, evaluates search terms and creative, and combines campaign evidence with counsellor feedback. The third month concentrates budget in stronger segments, improves weak handoffs and prepares the next admission-cycle decision. This is an operating roadmap rather than a promise that every course will reach a target cost or fill its batch in exactly three months."],
  ["Can we pause or cancel campaigns?", "Campaigns can be paused when seats fill, a batch changes, follow-up capacity is unavailable, policy issues arise or the agreed strategy requires it. Commercial notice periods and handover terms are stated in the proposal. Pausing can interrupt platform learning and remarketing momentum, so we explain the likely effect before a planned break. At exit, we provide an agreed summary and remove our access after handover; media balances, platform billing and external subscriptions remain under the institute's accounts."],
  ["Should we run SEO and ads together?", "Often, yes. Ads can capture current demand, test messages and support time-sensitive admissions, while SEO builds durable course, location and research visibility. Search-term and landing-page learning can inform content, and strong organic pages can improve paid journeys. The two services have different timelines and should be measured separately before examining their combined contribution. Read our coaching institute SEO service for the local, technical, content, authority and AI-visibility work that continues beyond paid media."],
  ["How do you handle student and parent data?", "We design forms to collect information relevant to the stated enquiry, restrict access according to the agreed tools and avoid placing sensitive details unnecessarily inside advertising platforms. Consent language, retention, CRM permissions and vendor settings must reflect the institute's actual legal and operational requirements. ErnestPath provides implementation support within scope but is not a substitute for legal advice. The institute remains responsible for its notices, lawful basis, internal use and response to data-subject requests."],
];

const serviceSchema = { "@context": "https://schema.org", "@type": "Service", "@id": "https://ernestpath.com/services/ads#service", name: "Google and Meta Ads for Coaching Institutes", serviceType: "Admission-focused paid media management", url: "https://ernestpath.com/services/ads", description: "Google Search Ads, Meta Ads, YouTube, remarketing, landing pages, creative strategy, conversion tracking, CRM integration and lead-quality optimisation for coaching institutes.", provider: { "@type": "Organization", "@id": "https://ernestpath.com/#organization", name: "ErnestPath", url: "https://ernestpath.com" }, areaServed: { "@type": "Country", name: "India" }, audience: { "@type": "BusinessAudience", audienceType: "Coaching institutes, training institutes and education businesses" }, hasOfferCatalog: { "@type": "OfferCatalog", name: "Advertising services for coaching institutes", itemListElement: services.map((s) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name: s.title, description: s.direct } })) } };
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([q,a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) };
const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://ernestpath.com" }, { "@type": "ListItem", position: 2, name: "Advertising", item: "https://ernestpath.com/services/ads" }] };
function safeJson(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }
const shell = "mx-auto w-[calc(100%-2rem)] max-w-7xl px-2 lg:px-8";
const label = "text-xs font-bold uppercase tracking-[0.2em] text-black/45";
const heading = "text-[clamp(3rem,6vw,6rem)] font-semibold leading-[0.95] tracking-[-0.065em]";

export default function AdsPage() {
  return <main id="main-content" className="overflow-hidden bg-[#f3f0e8] text-[#10110f]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson(serviceSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson(faqSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson(breadcrumbSchema)}} />

    <div className="bg-[#10110f] pt-28 text-[#f3f0e8]"><nav aria-label="Breadcrumb" className={`${shell} flex gap-2 py-5 text-sm text-white/55`}><Link href="/" className="hover:text-[#c9ff3d]">Home</Link><span>/</span><span aria-current="page" className="text-white/80">Google & Meta Ads</span></nav></div>
    <section className="bg-[#10110f] text-[#f3f0e8]" aria-labelledby="ads-title"><div className={`${shell} grid min-h-[730px] items-center gap-16 py-20 lg:grid-cols-[1.08fr_.92fr]`}>
      <div><p className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[.2em] text-white/65"><span className="h-2 w-2 rounded-full bg-[#c9ff3d]"/>Ads for coaching institutes</p><h1 id="ads-title" className="text-[clamp(3.7rem,7.5vw,7.6rem)] font-semibold leading-[.88] tracking-[-.075em]">Spend for admissions.<br/><span className="font-serif font-normal italic text-[#c9ff3d]">Not impressions.</span></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-white/65">ErnestPath connects Google, Meta and video campaigns with focused landing pages, reliable conversion tracking and counsellor feedback. The goal is not the largest lead count. It is a stronger flow of suitable prospects who understand the course and can progress toward a real admission.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/tools/admission-score" className="group inline-flex min-h-14 items-center justify-between gap-5 bg-[#c9ff3d] px-6 font-semibold text-black hover:-translate-y-1">Check your admission funnel <ArrowRight size={19}/></Link><a href="#system" className="inline-flex min-h-14 items-center justify-between gap-5 border border-white/20 px-6 text-white/80 hover:border-[#c9ff3d] hover:text-[#c9ff3d]">See the campaign system <ChevronDown size={18}/></a></div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-14 rounded-full bg-[#c9ff3d]/10 blur-3xl"/><div className="relative border border-white/15 bg-white/[.04] p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-sm text-white/55">Admission campaign</span><span className="rounded-full bg-[#c9ff3d] px-3 py-1 text-xs font-bold text-black">LIVE SYSTEM</span></div><div className="space-y-3 py-5">{[[MousePointerClick,"Relevant click"],[Layers3,"Course landing page"],[ClipboardCheck,"Qualified enquiry"],[MessageCircle,"Counsellor conversation"],[CircleCheck,"Admission outcome"]].map(([Icon,t],i)=><div key={String(t)} className="flex items-center gap-4 border border-white/10 bg-black/20 p-4"><span className="grid h-10 w-10 place-items-center bg-[#c9ff3d] text-black"><Icon size={19}/></span><span className="font-medium">{String(t)}</span><span className="ml-auto text-xs text-white/35">0{i+1}</span></div>)}</div><p className="border-t border-white/10 pt-4 text-sm leading-6 text-white/50">Every stage creates evidence. Media decisions improve when campaign data and admissions outcomes meet.</p></div></div>
    </div></section>

    <nav aria-label="Page sections" className="sticky top-0 z-30 border-b border-black/10 bg-[#f3f0e8]/90 backdrop-blur-xl"><div className={`${shell} flex gap-7 overflow-x-auto py-4 text-sm font-semibold`}>{[["#answer","Direct answer"],["#problems","Problems"],["#system","System"],["#services","Services"],["#measurement","Measurement"],["#process","Process"],["#faq","FAQ"]].map(([h,t])=><a key={h} href={h} className="whitespace-nowrap hover:text-black/55">{t}</a>)}</div></nav>

    <section id="answer" className="py-24 lg:py-32"><div className={`${shell} grid gap-12 lg:grid-cols-[.6fr_1.4fr]`}><p className={label}>Direct answer</p><div><h2 className={heading}>What are performance ads for coaching institutes?</h2><p className="mt-8 max-w-4xl text-xl leading-9 text-black/70">Performance advertising for a coaching institute is a measurable system that uses paid channels to attract suitable students or parents, explains the relevant programme on a focused destination, captures an informed enquiry and connects campaign source with counselling and admission outcomes. It may include Google Search Ads, Facebook and Instagram Ads, YouTube, remarketing, landing pages, forms, analytics and CRM integration. Its purpose is not merely to buy traffic or collect phone numbers. It is to create qualified admission opportunities at economics the institute can understand and improve.</p><div className="mt-10 grid gap-px bg-black/10 md:grid-cols-3">{[["Channels","Meet demand at the right stage"],["Experience","Turn attention into informed intent"],["Operations","Move leads toward real outcomes"]].map(([a,b])=><div key={a} className="bg-[#f3f0e8] p-7"><p className="font-semibold">{a}</p><p className="mt-2 text-sm leading-6 text-black/55">{b}</p></div>)}</div></div></div></section>

    <section className="border-y border-black/10 bg-white/45 py-24"><div className={shell}><p className={label}>Who we serve</p><h2 className="mt-5 max-w-4xl text-5xl font-semibold tracking-[-.05em]">Different courses need different campaign logic.</h2><div className="mt-14 grid gap-px bg-black/10 md:grid-cols-2">{audiences.map(([a,b],i)=><article key={a} className="bg-[#f7f4ed] p-8 lg:p-10"><div className="mb-8 flex items-center justify-between"><span className="text-xs font-bold text-black/35">0{i+1}</span><Users size={18}/></div><h3 className="text-2xl font-semibold">{a}</h3><p className="mt-4 leading-7 text-black/60">{b}</p></article>)}</div></div></section>

    <section id="problems" className="bg-[#10110f] py-24 text-[#f3f0e8] lg:py-32"><div className={shell}><p className="text-xs font-bold uppercase tracking-[.2em] text-white/40">Why campaigns fail</p><h2 className={`${heading} mt-6 max-w-5xl`}>The platform is rarely the only problem.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-white/55">An ad account sits inside a larger admissions system. Weak positioning, an unclear offer, a slow page, inaccurate events or inconsistent follow-up can make good media buying look ineffective. We diagnose the chain before prescribing more spend.</p><div className="mt-16 grid gap-5 md:grid-cols-2">{failures.map(([a,b],i)=><article key={a} className="border border-white/10 p-7 lg:p-9"><div className="flex gap-5"><span className="text-sm font-bold text-[#c9ff3d]">{String(i+1).padStart(2,"0")}</span><div><h3 className="text-xl font-semibold">{a}</h3><p className="mt-4 leading-7 text-white/55">{b}</p></div></div></article>)}</div></div></section>

    <section id="system" className="py-24 lg:py-32"><div className={shell}><p className={label}>ErnestPath admission campaign system</p><div className="mt-6 grid gap-10 lg:grid-cols-2"><h2 className={heading}>Eight connected layers. One measurable journey.</h2><p className="max-w-xl text-lg leading-8 text-black/60">Clicks do not become admissions automatically. Each layer must give the next one enough relevance and information to work. This framework keeps campaigns tied to the real education decision rather than isolated inside an advertising dashboard.</p></div><div className="mt-16 grid gap-px bg-black/10 sm:grid-cols-2 lg:grid-cols-4">{system.map(([a,b],i)=><article key={a} className="bg-[#f3f0e8] p-7"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#c9ff3d] text-sm font-bold">{i+1}</span><h3 className="mt-8 text-2xl font-semibold">{a}</h3><p className="mt-4 text-sm leading-7 text-black/60">{b}</p></article>)}</div></div></section>

    <section id="services" className="border-y border-black/10 bg-white/45 py-24 lg:py-32"><div className={shell}><p className={label}>Complete service scope</p><h2 className={`${heading} mt-6 max-w-5xl`}>Everything required between budget and admission evidence.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-black/60">The final scope follows your priorities and existing capabilities. These modules show the complete system we can address; they are not a claim that every institute must buy every channel or integration.</p><div className="mt-16 space-y-6">{services.map((s,i)=><article key={s.title} className="grid gap-8 border border-black/10 bg-[#f3f0e8] p-7 lg:grid-cols-[.08fr_.42fr_.5fr] lg:p-10"><div><span className="grid h-12 w-12 place-items-center bg-[#10110f] text-[#c9ff3d]"><s.icon size={22}/></span><span className="mt-5 block text-xs font-bold text-black/35">{String(i+1).padStart(2,"0")}</span></div><div><h3 className="text-3xl font-semibold tracking-[-.04em]">{s.title}</h3><p className="mt-5 font-semibold leading-7">{s.direct}</p><p className="mt-4 text-sm leading-7 text-black/55"><strong className="text-black">Problem: </strong>{s.problem}</p><p className="mt-4 text-sm leading-7 text-black/55"><strong className="text-black">Our approach: </strong>{s.solution}</p></div><div className="grid content-start gap-3 sm:grid-cols-2">{s.includes.map(x=><div key={x} className="flex gap-3 border-t border-black/10 pt-3 text-sm"><Check size={16} className="mt-0.5 shrink-0"/>{x}</div>)}</div></article>)}</div></div></section>

    <section className="py-24 lg:py-32"><div className={shell}><p className={label}>Channel roles</p><h2 className={`${heading} mt-6 max-w-5xl`}>Choose the channel for the decision—not the trend.</h2><div className="mt-14 overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left"><thead><tr className="border-b-2 border-black">{["Channel","Primary role","Audience state","Best used for","Important limitation"].map(h=><th key={h} className="p-4 text-xs uppercase tracking-wider">{h}</th>)}</tr></thead><tbody>{channels.map(r=><tr key={r[0]} className="border-b border-black/10 align-top">{r.map((c,i)=><td key={c} className={`p-4 text-sm leading-6 ${i===0?"font-bold":"text-black/60"}`}>{c}</td>)}</tr>)}</tbody></table></div><div className="mt-10 border-l-4 border-[#c9ff3d] bg-white/55 p-7"><p className="max-w-4xl leading-7 text-black/65"><strong className="text-black">About Performance Max:</strong> it can be useful when conversion signals, assets, location controls and downstream evidence are strong enough to guide automation. We do not use it as a default replacement for strategy or search-term understanding. The campaign type is selected only when its reach and automation match the institute&apos;s objective and measurement maturity.</p></div></div></section>

    <section className="bg-[#10110f] py-24 text-[#f3f0e8] lg:py-32"><div className={`${shell} grid gap-14 lg:grid-cols-2`}><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/40">Creative system</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.055em]">Give people a reason to stop—and a reason to believe.</h2><p className="mt-7 text-lg leading-8 text-white/55">A useful ad is a compact decision aid. It identifies a relevant problem, shows why the programme may fit, provides proportionate evidence and makes the next step clear. We plan a portfolio rather than betting the budget on one ‘winning’ poster.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{[["Hook","Name a real goal, obstacle, moment or question."],["Fit","Clarify course, learner, level, mode and location."],["Mechanism","Explain how teaching, projects, tests or mentoring works."],["Evidence","Use verified outcomes, faculty, student work or reviews."],["Objection","Address time, confidence, eligibility, format or process."],["Action","Offer counselling, demo or assessment appropriate to intent."]].map(([a,b])=><div key={a} className="bg-[#10110f] p-6"><h3 className="text-xl font-semibold text-[#c9ff3d]">{a}</h3><p className="mt-3 text-sm leading-6 text-white/55">{b}</p></div>)}</div></div></section>

    <section className="py-24 lg:py-32"><div className={`${shell} grid gap-14 lg:grid-cols-[.85fr_1.15fr]`}><div><p className={label}>Lead quality</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.055em]">The cheapest lead can be the most expensive.</h2><p className="mt-7 text-lg leading-8 text-black/60">Lead quality is a shared operating metric. Marketing must attract and inform the right people; the website must capture relevant context; counsellors must respond and update outcomes; management must define what ‘qualified’ means. When any link is missing, cost per lead becomes an incomplete answer.</p><Link href="/services/website-development" className="mt-8 inline-flex items-center gap-2 border-b border-black pb-1 font-semibold">Explore admission-focused websites <ArrowRight size={17}/></Link></div><div className="space-y-3">{[["1. Define","Course fit, geography, eligibility, timing and genuine intent."],["2. Capture","Use message, page and form fields to set expectations."],["3. Route","Send source and course context to the right counsellor."],["4. Respond","Agree ownership, speed, attempts and useful conversation."],["5. Record","Update qualified, demo, visit, application and admission stages."],["6. Learn","Return outcome patterns to campaigns, creative and landing pages."]].map(([a,b])=><div key={a} className="flex gap-6 border-t border-black/10 py-5"><strong className="w-24 shrink-0">{a}</strong><p className="text-black/60">{b}</p></div>)}</div></div></section>

    <section id="measurement" className="bg-[#c9ff3d] py-24 lg:py-32"><div className={shell}><p className={label}>Measurement that reaches the business</p><h2 className={`${heading} mt-6 max-w-5xl`}>Measure movement, not just media activity.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-black/65">Attribution is never perfect, but a defined funnel is far more useful than a pile of platform metrics. We document each stage, how it is recorded and which gaps remain.</p><div className="mt-14 grid gap-px bg-black/20 md:grid-cols-2 lg:grid-cols-3">{metrics.map(([a,b],i)=><article key={a} className="bg-[#c9ff3d] p-7"><span className="text-xs font-bold">0{i+1}</span><h3 className="mt-7 text-2xl font-semibold">{a}</h3><p className="mt-4 text-sm leading-7 text-black/65">{b}</p></article>)}</div></div></section>

    <section className="py-24 lg:py-32"><div className={shell}><p className={label}>The first 90 days</p><h2 className={`${heading} mt-6 max-w-4xl`}>Build. Learn. Concentrate.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-black/60">Three months can create a much stronger campaign and admissions operating system. It cannot responsibly guarantee a ranking, lead count, cost or filled batch. Progress depends on demand, evidence, budget, approvals, data volume and follow-up quality.</p><div className="mt-14 grid gap-5 lg:grid-cols-3">{roadmap.map(([m,g,d],i)=><article key={m} className={`${i===1?"bg-[#10110f] text-white":"border border-black/10"} p-8`}><p className={`text-xs font-bold uppercase tracking-wider ${i===1?"text-[#c9ff3d]":"text-black/40"}`}>{m}</p><h3 className="mt-7 text-2xl font-semibold">{g}</h3><p className={`mt-5 leading-7 ${i===1?"text-white/55":"text-black/60"}`}>{d}</p></article>)}</div></div></section>

    <section id="process" className="border-y border-black/10 bg-white/45 py-24 lg:py-32"><div className={shell}><p className={label}>How we work</p><h2 className={`${heading} mt-6 max-w-5xl`}>A twelve-step path from assumptions to evidence.</h2><div className="mt-16 grid gap-px bg-black/10 md:grid-cols-2">{process.map(([n,a,b])=><article key={n} className="bg-[#f7f4ed] p-8"><span className="text-xs font-bold text-black/35">{n}</span><h3 className="mt-7 text-2xl font-semibold">{a}</h3><p className="mt-4 leading-7 text-black/60">{b}</p></article>)}</div></div></section>

    <section className="py-24 lg:py-32"><div className={shell}><p className={label}>A specialist difference</p><h2 className={`${heading} mt-6 max-w-5xl`}>Not generic lead generation with an education label.</h2><div className="mt-14 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="border-b-2 border-black"><th className="p-4">Decision area</th><th className="p-4">Routine campaign</th><th className="p-4">ErnestPath approach</th></tr></thead><tbody>{comparison.map(([a,b,c])=><tr key={a} className="border-b border-black/10 align-top"><td className="p-4 font-semibold">{a}</td><td className="p-4 text-black/50"><span className="flex gap-2"><X size={16} className="mt-1 shrink-0"/>{b}</span></td><td className="p-4"><span className="flex gap-2"><Check size={16} className="mt-1 shrink-0"/>{c}</span></td></tr>)}</tbody></table></div></div></section>

    <section className="bg-[#10110f] py-24 text-[#f3f0e8]"><div className={`${shell} grid gap-14 lg:grid-cols-2`}><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/40">Scope clarity</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.055em]">Know what is included before the first rupee is spent.</h2><p className="mt-6 leading-7 text-white/55">Every proposal specifies channels, courses, locations, landing pages, creative responsibilities, tracking, integrations, reporting, access and approval roles. Clear boundaries protect speed and accountability.</p></div><div className="grid gap-8 sm:grid-cols-2"><div><h3 className="font-semibold text-[#c9ff3d]">Usually defined in scope</h3><ul className="mt-5 space-y-3 text-sm text-white/60">{["Campaign setup and management","Agreed landing-page work","Ad copy and creative direction","Tracking and analytics configuration","Lead-flow or CRM integration","Optimisation and reporting rhythm","Account access and handover"].map(x=><li key={x} className="flex gap-2"><Check size={15} className="mt-1 shrink-0"/>{x}</li>)}</ul></div><div><h3 className="font-semibold text-[#c9ff3d]">Separate or never promised</h3><ul className="mt-5 space-y-3 text-sm text-white/60">{["Media spend paid to platforms","External software subscriptions","Large photo or video production","A guaranteed lead or admission count","Fabricated reviews, results or urgency","Platform approval or reinstatement","Unlimited pages, assets or revisions"].map(x=><li key={x} className="flex gap-2"><X size={15} className="mt-1 shrink-0"/>{x}</li>)}</ul></div></div></div></section>

    <section id="faq" className="py-24 lg:py-32"><div className={`${shell} grid gap-12 lg:grid-cols-[.6fr_1.4fr]`}><div><p className={label}>Frequently asked questions</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.055em]">Clear answers before you commit.</h2><p className="mt-6 leading-7 text-black/55">These answers address common commercial, operational and technical questions. Your proposal remains the final definition of scope.</p></div><div className="border-t border-black/15">{faqs.map(([q,a])=><details key={q} className="group border-b border-black/15"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 text-lg font-semibold"><span>{q}</span><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-black/15 transition-transform group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-7 pr-10 leading-7 text-black/60">{a}</p></details>)}</div></div></section>

    <section className="px-4 pb-4"><div className="mx-auto max-w-7xl bg-[#c9ff3d] px-6 py-16 lg:px-14 lg:py-20"><div className="grid items-end gap-10 lg:grid-cols-[1fr_auto]"><div><p className={label}>Start with the current funnel</p><h2 className="mt-5 max-w-4xl text-[clamp(3rem,6vw,6rem)] font-semibold leading-[.92] tracking-[-.065em]">Find where your next admission is being lost.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-black/65">Use the free Admission Score to review the digital path, or explore the SEO and website systems that support paid growth before and after the click.</p></div><div className="flex flex-col gap-3"><Link href="/tools/admission-score" className="group inline-flex min-h-14 items-center justify-between gap-6 bg-[#10110f] px-6 font-semibold text-white">Get your free score <ArrowRight size={18} className="group-hover:translate-x-1"/></Link><Link href="/services/seo" className="inline-flex min-h-12 items-center justify-between gap-6 border border-black/30 px-6 font-semibold">Explore institute SEO <ArrowRight size={17}/></Link></div></div></div></section>
  </main>;
}
